<?php declare(strict_types=1);

namespace Alumni\Infrastructure\Repository\DB\Mapper;

use Alumni\Domain\Entity\AttachmentReport;
use Alumni\Domain\Entity\Report;
use Alumni\Infrastructure\Entity\AttachmentsReportDoctrine;
use Alumni\Infrastructure\Entity\ReportsDoctrine;

/**
 * Mapper for converting between AttachmentReport domain entities and AttachmentsReportDoctrine infrastructure entities.
 * 
 * This mapper handles the bidirectional conversion between the domain layer
 * (AttachmentReport) and the infrastructure layer (AttachmentsReportDoctrine),
 * ensuring proper mapping of all attachment properties and relationships.
 */
class AttachmentsReportMapper
{

    /**
     * Converts an AttachmentsReportDoctrine entity to an AttachmentReport domain entity.
     * 
     * This method maps all properties from the Doctrine entity to the domain entity,
     * including the relationship with the parent report. The report parameter is required
     * to establish the bidirectional relationship in the domain model.
     * 
     * @param AttachmentsReportDoctrine $attachmentReportDoctrine The Doctrine entity to convert
     * @param Report $report The domain report entity this attachment belongs to
     * @return AttachmentReport The converted domain entity
     */
    public function toDomain(
        AttachmentsReportDoctrine $attachmentReportDoctrine,
        Report $report
    ): AttachmentReport {
        return new AttachmentReport(
            id: $attachmentReportDoctrine->getId(),
            filename: $attachmentReportDoctrine->getFilename(),
            originalName: $attachmentReportDoctrine->getOriginalName(),
            mimeType: $attachmentReportDoctrine->getMimeType(),
            fileSize: $attachmentReportDoctrine->getFileSize(),
            filePath: $attachmentReportDoctrine->getFilePath(),
            uploadedAt: $attachmentReportDoctrine->getUploadedAt(),
            report: $report
        );
    }

    /**
     * Converts an AttachmentReport domain entity to an AttachmentsReportDoctrine entity.
     * 
     * This method creates a new Doctrine entity and maps all properties from the
     * domain entity, including the relationship with the parent report. The report
     * parameter is required to establish the bidirectional relationship in the
     * Doctrine entity.
     * 
     * Note: The ID is not set as it will be generated by Doctrine when persisting.
     * 
     * @param AttachmentReport $attachmentReport The domain entity to convert
     * @param ReportsDoctrine $report The Doctrine report entity this attachment belongs to
     * @return AttachmentsReportDoctrine The converted Doctrine entity
     */
    public function toDoctrine(
        AttachmentReport $attachmentReport,
        ReportsDoctrine $report
    ): AttachmentsReportDoctrine {
        $attachmentReportDoctrine = new AttachmentsReportDoctrine();
        $attachmentReportDoctrine->setFilename($attachmentReport->filename);
        $attachmentReportDoctrine->setOriginalName($attachmentReport->originalName);
        $attachmentReportDoctrine->setMimeType($attachmentReport->mimeType);
        $attachmentReportDoctrine->setFileSize($attachmentReport->fileSize);
        $attachmentReportDoctrine->setFilePath($attachmentReport->filePath);
        $attachmentReportDoctrine->setUploadedAt($attachmentReport->uploadedAt);
        $attachmentReportDoctrine->setReportId($report);
        
        return $attachmentReportDoctrine;
    }
}

