<?php declare(strict_types=1);

namespace Alumni\Infrastructure\Repository\DB\Mapper;

use Alumni\Domain\Entity\Report;
use Alumni\Infrastructure\Entity\ReportsDoctrine;

/**
 * Mapper for converting between Report domain entities and ReportsDoctrine infrastructure entities.
 * 
 * This mapper handles the bidirectional conversion between the domain layer (Report)
 * and the infrastructure layer (ReportsDoctrine), including nested entities like
 * User and AttachmentReport. It uses a two-step process to avoid circular dependencies
 * when mapping attachments.
 */
class ReportsMapper
{
    /**
     * Creates a new instance of ReportsMapper.
     * 
     * @param UserMapper $userMapper Mapper for converting User entities
     * @param AttachmentsReportMapper $attachmentsReportMapper Mapper for converting AttachmentReport entities
     */
    public function __construct(
        private readonly UserMapper $userMapper,
        private readonly AttachmentsReportMapper $attachmentsReportMapper
    ) {}

    /**
     * Converts a ReportsDoctrine entity to a Report domain entity.
     * 
     * This method uses a two-step process to avoid circular dependencies:
     * 1. First creates the Report without attachments
     * 2. Then maps the attachments using the already-created Report reference
     * 
     * The final Report is reconstructed with all attachments included.
     * 
     * @param ReportsDoctrine $reportsDoctrine The Doctrine entity to convert
     * @return Report The converted domain entity with all attachments
     */
    public function toDomain(ReportsDoctrine $reportsDoctrine): Report
    {
        // First create the report domain object without attachments to avoid circular dependency
        $report = new Report(
            id: $reportsDoctrine->getId(),
            type: $reportsDoctrine->getType(),
            topic: $reportsDoctrine->getTopic(),
            description: $reportsDoctrine->getDescription(),
            createdAt: $reportsDoctrine->getCreatedAt(),
            updatedAt: $reportsDoctrine->getUpdatedAt(),
            status: $reportsDoctrine->getStatus(),
            user: $this->userMapper->toDomain($reportsDoctrine->getAuthor()),
            attachments: []
        );

        // Now map attachments, passing the already-converted report
        $attachments = [];
        if ($reportsDoctrine->getAttachments() !== null) {
            foreach ($reportsDoctrine->getAttachments() as $attachment) {
                $attachments[] = $this->attachmentsReportMapper->toDomain($attachment, $report);
            }
        }

        // Return a new Report with attachments
        return new Report(
            id: $report->id,
            type: $report->type,
            topic: $report->topic,
            description: $report->description,
            createdAt: $report->createdAt,
            updatedAt: $report->updatedAt,
            status: $report->status,
            user: $report->user,
            attachments: $attachments
        );
    }

    /**
     * Converts a Report domain entity to a ReportsDoctrine entity.
     * 
     * This method creates a new Doctrine entity and maps all properties from the
     * domain entity, including the nested User entity and all AttachmentReport
     * entities. The attachments are added to the Doctrine entity using the
     * addAttachment() method to maintain bidirectional relationships.
     * 
     * Note: The ID is not set as it will be generated by Doctrine when persisting
     * new entities, or should be set from the domain entity's ID for existing entities.
     * 
     * @param Report $report The domain entity to convert
     * @return ReportsDoctrine The converted Doctrine entity with all attachments
     */
    public function toDoctrine(Report $report): ReportsDoctrine
    {
        $reportsDoctrine = new ReportsDoctrine();
        $reportsDoctrine->setType($report->type);
        $reportsDoctrine->setTopic($report->topic);
        $reportsDoctrine->setDescription($report->description);
        $reportsDoctrine->setCreatedAt($report->createdAt);
        $reportsDoctrine->setUpdatedAt($report->updatedAt);
        $reportsDoctrine->setStatus($report->status);
        $reportsDoctrine->setAuthor($this->userMapper->toDoctrine($report->user));

        // Map all attachments and add them to the Doctrine entity
        foreach ($report->attachments as $attachment) {
            $reportsDoctrine->addAttachment($this->attachmentsReportMapper->toDoctrine($attachment, $reportsDoctrine));
        }
        
        return $reportsDoctrine;
    }
}